### PR TITLE
fix: types & config fixes

### LINKED ISSUE #30: Custom type renderer is losing TypeScript semantics in generated docs
### Have you used AI?

None

## Summary

The custom TypeDoc rendering in this repo is simplifying webpack types too aggressively, and the generated docs end up losing important TypeScript semantics.

This looks like the main correctness issue in `webpack-doc-kit`: the pipeline completes, but the published output can misrepresent the actual webpack API surface.

## Why this matters

`webpack-doc-kit` exists to turn webpack’s TypeScript definitions into reliable API docs. If the custom renderer changes the meaning of types during generation, the docs become misleading even when CI and deployment succeed.

In other words, this is not just a formatting issue. It affects the correctness of the generated documentation.

## Root cause

The problem appears to be in the custom type resolver here:

- `plugins/theme/partials/types.mjs`

The resolver currently collapses several TypeDoc type shapes too aggressively:

- `reference` types return only `type.name`, which drops generic parameters
- `tuple` types are rendered as unions instead of tuple syntax
- `conditional` types are rendered as `trueType|falseType`, which removes the condition entirely
- `optional` / `indexedAccess` types are flattened and lose structure
- `reflection` types are rendered as plain `object`, which also discards useful shape information

### 1. Generic types lose their parameters

In generated docs, types like `Map`, `ReadonlySet`, and `Record` are emitted without their type arguments.

Examples:
- `pages/v5.x/webpack/namespaces/esm.md`
- `pages/v5.x/webpack/namespaces/sharing.md`

Observed output includes entries like:

- `{Map}`
- `{ReadonlySet}`
- `{Record}`

This drops the information that makes those types useful.

### 2. Tuples are rendered as unions

Tuple-like values are emitted in union form.

Example:
- `pages/v5.x/webpack/namespaces/dependencies.md`

Observed output includes:

- `{number|number|number}`

That changes the meaning from “fixed-position tuple” to “union of values”.

### 3. Conditional types are not preserved

Conditional types are reduced to a union of the true/false branches, which is not equivalent to the original type and can be misleading.

## Expected behavior

The generated docs should preserve the semantic structure of webpack’s TypeScript types as closely as possible, including:

- generic parameters
- tuple syntax
- conditional type structure
- indexed access / optional wrappers where relevant
- richer rendering for reflected object/function shapes when available

## Actual behavior

The current renderer produces simpler output, but in many cases that output is semantically inaccurate.

## Relevant code

- `plugins/theme/partials/types.mjs`

In particular, the issue seems centered on the custom `resolve()` logic used by `someType()`.

## Suggested direction

I think this should be treated as a documentation correctness bug rather than a presentation enhancement.

A fix would likely involve:
- preserving `reference` type arguments
- rendering tuples as tuples
- keeping conditional types in conditional form
- handling indexed access / optional types explicitly
- avoiding fallback-to-`object` unless there is no better representation

## Additional note

There may also be a separate DX issue for local contributors: `generate-md.mjs` assumes a sibling `./webpack` checkout, but that setup requirement is not very obvious from the README. That seems secondary, though. The main issue is the correctness of generated types.

### Link to Minimal Reproduction and step to  reproduce

This issue is reproducible directly in this repository:

https://github.com/webpack/webpack-doc-kit

Steps to reproduce:
1. Clone `webpack/webpack-doc-kit`
2. Check out the webpack commit referenced in `HEAD_COMMIT` into a sibling `./webpack` directory, matching the repo's CI workflow
3. Run `npm ci`
4. Run `npm run generate-docs`
5. Inspect generated files under `pages/v5.x/`

Examples of incorrect output already present in the generated docs:
- `pages/v5.x/webpack/namespaces/esm.md`
  - `fileTimestamps` and `contextTimestamps` are rendered as `{Map}` with generic type arguments removed
- `pages/v5.x/webpack/namespaces/sharing.md`
  - return type is rendered as `{Record}` with no key/value shape
- `pages/v5.x/webpack/namespaces/dependencies.md`
  - tuple-like types are rendered as unions such as `{number|number|number}`

Relevant implementation area:
- `plugins/theme/partials/types.mjs`

The issue appears to come from the custom type resolver simplifying TypeDoc types too aggressively:
- generic references lose type parameters
- tuples are converted into unions
- conditional types lose their conditional structure
- some structured/reflection types degrade to plain `object`

### Expected Behavior

The generated documentation should preserve the semantics of webpack's TypeScript types as closely as possible.

Expected behavior:
- generic types should keep their type arguments
- tuples should be rendered as tuples, not unions
- conditional types should retain their conditional form
- indexed/optional/reflection-based types should not be collapsed in ways that change meaning

The docs generator may choose a simplified presentation, but it should not produce output that materially changes the original type information.

### Actual Behavior

The generated documentation drops or changes TypeScript type information during rendering.

Observed examples:
- generic reference types are emitted without type parameters, e.g. `{Map}`, `{ReadonlySet}`, `{Record}`
- tuple types are rendered as unions, e.g. `{number|number|number}`
- conditional types are flattened into unions of branches
- some structured/reflection types are reduced to plain `object`

As a result, the generated docs are simpler than the source types but semantically inaccurate.

### Environment

```shell
Packages:
  webpack-doc-kit: current `main`
  webpack: commit from `HEAD_COMMIT`
  typedoc: ^0.28.17
  typedoc-plugin-markdown: ^4.10.0
  @node-core/doc-kit: ^1.0.1
```

### Is this a regression?

None

### Last Working Version

_No response_

### Additional Context

The issue appears to originate in the custom renderer at `plugins/theme/partials/types.mjs`.

This seems to be the core correctness risk in the project: `webpack-doc-kit` is a type-to-doc pipeline, so if the custom serializer changes the meaning of types, the generated API docs become unreliable even when CI and deployment succeed.

Relevant generated examples:
- `pages/v5.x/webpack/namespaces/esm.md`
- `pages/v5.x/webpack/namespaces/sharing.md`
- `pages/v5.x/webpack/namespaces/dependencies.md`

### PR DESCRIPTION
**Pull request by sujalgoel**
## Summary

Fixes #30

The custom type resolver in `plugins/theme/partials/types.mjs` was collapsing TypeScript types too aggressively, producing semantically inaccurate documentation output. This PR restores the correct semantics now that `@node-core/doc-kit` supports generic types.

### Changes

- **`reference` types** now include generic type arguments
  - Before: `{Map}`, `{ReadonlySet}`, `{Record}`
  - After: `{Map<string, number>}`, `{ReadonlySet<string>}`, `{Record<string, string|string[]|T>}`

- **`tuple` types** now render as tuple syntax instead of union syntax
  - Before: `{number|number|number}`
  - After: `{[number, number, number]}`

- **`conditional` types** now preserve the full conditional structure
  - Before: `{TrueType|FalseType}`
  - After: `{CheckType extends ExtendsType ? TrueType : FalseType}`

- **`optional` tuple members** now render with a trailing `?` suffix

- **`indexedAccess` types** now render as `T[K]` instead of just `T`

### Verification

After regenerating docs with `npm run generate-docs`, the affected files show correct output:

- `pages/v5.x/webpack/namespaces/esm.md`: `{Map<string, number>}`, `{ReadonlySet<string>}`, `{Iterable<Chunk>}`
- `pages/v5.x/webpack/namespaces/sharing.md`: `{Record<string, string|string[]|T>}`
- `pages/v5.x/webpack/namespaces/dependencies.md`: `{[number, number]}` instead of `{number|number}`

The regenerated `pages/v5.x/` output is included in this PR.

### CODE REVIEW

File: plugins/theme/partials/types.mjs [hunk 1]
```diff
@@ -17,15 +23,17 @@ const resolve = type => {
...
-      return union(type.elements);
+      return `[${(type.elements ?? []).map(resolve).join(', ')}]`;
 
     case 'union':
     case 'intersection':
       return union(type.types);
 
     case 'optional':
+      return resolve(type.elementType) + '?';
+
```
Comment (avivkeller) [inline plugins/theme/partials/types.mjs]: When a type is optional, we should just return the type, there's other ways to say it's optional in doc-kit

**Review by avivkeller — CHANGES_REQUESTED** [review]

File: plugins/theme/partials/types.mjs [hunk 2]
```diff
@@ -5,9 +5,15 @@ const resolve = type => {
 
   switch (type.type) {
     case 'intrinsic':
-    case 'reference':
       return type.name;
 
+    case 'reference': {
```
Comment (avivkeller) [inline plugins/theme/partials/types.mjs]: We can merge this with the above case

File: plugins/theme/partials/types.mjs [hunk 3]
```diff
@@ -17,13 +23,15 @@ const resolve = type => {
       return resolve(type.elementType) + '[]';
 
     case 'tuple':
-      return union(type.elements);
+      return `Tuple<${(type.elements ?? []).map(resolve).join(', ')}>`;
```
Comment (avivkeller) [inline plugins/theme/partials/types.mjs]: nit: let's make `union(type.elements, ', ')` work

**Review by avivkeller — APPROVED** [review]
Thank you!

**Comment by avivkeller** [comment]
I'll regenerate the docs to make the check pass when I get a chance

File: plugins/theme/partials/types.mjs (hunk 2 above)
Comment (sujalgoel) [reply plugins/theme/partials/types.mjs]: Done, merged `intrinsic` and `reference` into one case.
